#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
test:
  clients:
    type: local
    number: 5
  rounds:
  - label: Change car owner.
    txDuration:
    - 30
    rateControl:
    - type: fixed-backlog
      opts:
        unfinished_per_client: 5
    arguments:
      assets: 1000
    callback: benchmarks/samples/fabric/fabcar/changeCarOwner.js
  - label: Query all cars.
    txDuration:
    - 30
    rateControl:
    - type: fixed-backlog
      opts:
        unfinished_per_client: 5
    arguments:
      assets: 1000
      startKey: '1'
      endKey: '50'
    callback: benchmarks/samples/fabric/fabcar/queryAllCars.js
  - label: Query a car.
    txDuration:
    - 30
    rateControl:
    - type: fixed-backlog
      opts:
        unfinished_per_client: 5
    arguments:
      assets: 1000
    callback: benchmarks/samples/fabric/fabcar/queryCar.js
  - label: Create a car.
    txDuration:
    - 30
    rateControl:
    - type: fixed-backlog
      opts:
        unfinished_per_client: 5
    callback: benchmarks/samples/fabric/fabcar/createCar.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
