test:
  name: simple
  description: >-
    This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  workers:
    type: local
    number: 1
  rounds:
    - label: open
      description: >-
        Test description for the opening of an account through the deployed
        chaincode
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: benchmarks/scenario/simple/open.js
        arguments:
          money: 10000
    - label: query
      description: Test description for the query performance of the deployed chaincode
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: benchmarks/scenario/simple/query.js
    - label: transfer
      description: Test description for transfering money between accounts
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: benchmarks/scenario/simple/transfer.js
        arguments:
          money: 100
monitor:
  type:
    - docker
  docker:
    name:
      - all
  interval: 1
