test:
  name: Marble Benchmarking
  description: Perf test marbles
  workers:
    type: local
    number: 1
  rounds:
    - label: init
      description: >-
        Create marbles. Lots of them. So many marbles that if you lost them, you
        would still be sane.
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: benchmarks/samples/fabric/marbles/init.js
    - label: query
      description: >-
        Query marbles. Query them until you are bored of querying them. Then
        query them some more.
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: benchmarks/samples/fabric/marbles/query.js
observer:
  type: prometheus
  interval: 1
monitor:
  type:
    - docker
    - process
    - prometheus
  docker:
    containers:
      - all
    charting:
      polar:
        metrics:
          - all
      bar:
        metrics:
          - Memory(max)
  process:
    processes:
      - command: node
        arguments: fabricClientWorker.js
        multiOutput: avg
    charting:
      bar:
        metrics:
          - all
  prometheus:
    push_url: 'http://localhost:9091'
    url: 'http://localhost:9090'
    metrics:
      ignore:
        - prometheus
        - pushGateway
        - cadvisor
        - grafana
        - node-exporter
      include:
        Endorse Time (s):
          query: >-
            rate(endorser_propsal_duration_sum{chaincode="marbles:v0"}[5m])/rate(endorser_propsal_duration_count{chaincode="marbles:v0"}[5m])
          step: 1
          label: instance
          statistic: avg
        Max Memory (MB):
          query: 'sum(container_memory_rss{name=~".+"}) by (name)'
          step: 10
          label: name
          statistic: max
          multiplier: 0.000001
    charting:
      polar:
        metrics:
          - Max Memory (MB)
      bar:
        metrics:
          - all
